name: Lint, Test and Run
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Lint with eslint
        run: npm run lint
  build:
    runs-on: ubuntu-22.04
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Build with ncc
        run: npm run build
  test:
    runs-on: ubuntu-22.04
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test
  run:
    runs-on: ubuntu-22.04
    needs:
      - build
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the Action
        uses: ./
        with:
          version: 5.5.2
          csproj-files: files/csproj/TestProject.csproj
          npm-files: files/npm/package.json
          setuppy-files: files/setuppy/setup.py
